apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sysops-ingress
spec:
  tls:
  - hosts:
    - sysops.example.com
    secretName: sysops-secret
  rules:
  - host: sysops.example.com
    http:
      paths:
      - path: /statics
        pathType: Prefix
        backend:
          service:
            name: statics-svc
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-svc
            port:
              number: 80